### ISSUE TITLE
TypeError: reset() got an unexpected keyword argument 'seed'

### ISSUE THREAD

**Issue by sumodqnx** [LucasAlegre/sumo-rl#106]
I am new in SUMO and trying to use your code for a research. 

This error is what I got by running:
`python experiments/dqn_2way-single-intersection.py`

```
 Retrying in 1 seconds
Step #0.00 (0ms ?*RT. ?UPS, TraCI: 3ms, vehicles TOT 0 ACT 0 BUF 0)                      
Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Traceback (most recent call last):
  File "/home/tl/Downloads/sumo-rl-master/experiments/dqn_2way-single-intersection.py", line 34, in <module>
    model.learn(total_timesteps=100000)
  File "/home/tl/anaconda3/envs/kuo/lib/python3.9/site-packages/stable_baselines3/dqn/dqn.py", line 264, in learn
    return super().learn(
  File "/home/tl/anaconda3/envs/kuo/lib/python3.9/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 332, in learn
    total_timesteps, callback = self._setup_learn(
  File "/home/tl/anaconda3/envs/kuo/lib/python3.9/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 308, in _setup_learn
    return super()._setup_learn(
  File "/home/tl/anaconda3/envs/kuo/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 446, in _setup_learn
    self._last_obs = self.env.reset()  # pytype: disable=annotation-type-mismatch
  File "/home/tl/anaconda3/envs/kuo/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 63, in reset
    obs = self.envs[env_idx].reset()
  File "/home/tl/anaconda3/envs/kuo/lib/python3.9/site-packages/stable_baselines3/common/monitor.py", line 79, in reset
    return self.env.reset(**kwargs)
  File "/home/tl/anaconda3/envs/kuo/lib/python3.9/site-packages/sumo_rl/environment/env.py", line 187, in reset
    super().reset(seed=seed, return_info=return_info, **kwargs)
```

Pip list:
```
Package            Version
------------------ ---------
certifi            2022.6.15
cloudpickle        2.1.0
cycler             0.11.0
fonttools          4.37.1
gym                0.21.0
gym-notices        0.0.8
importlib-metadata 4.12.0
kiwisolver         1.4.4
matplotlib         3.5.3
numpy              1.23.2
packaging          21.3
pandas             1.4.3
PettingZoo         1.18.1
Pillow             9.2.0
pip                22.1.2
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2022.2.1
setuptools         63.4.1
six                1.16.0
stable-baselines3  1.6.0
sumo-rl            1.3.0
sumolib            1.14.1
torch              1.12.1
traci              1.14.1
typing_extensions  4.3.0
wheel              0.37.1
zipp               3.8.1
```

Any feedback will be highly appreciated.

**Comment by Mad-Chuck** [comment]
This probably has to do with incorrect gym version. Try upgrading your gym package with:
```cmd
pip install gym --upgrade
```
Another temporary fix would to comment out line number 187 in file `sumo_rl\environment\env.py`, so that the method `reset()` looks like this:
```python
    def reset(self, seed: Optional[int] = None, return_info=False, **kwargs):
        #super().reset(seed=seed, return_info=return_info, **kwargs)
        
        if self.run != 0:
            self.close()
            self.save_csv(self.out_csv_name, self.run)
        self.run += 1
        self.metrics = []

        if seed is not None:
            self.sumo_seed = seed
        self._start_simulation()

        self.traffic_signals = {ts: TrafficSignal(self, 
                                                  ts, 
                                                  self.delta_time, 
                                                  self.yellow_time, 
                                                  self.min_green, 
                                                  self.max_green, 
                                                  self.begin_time,
                                                  self.reward_fn,
                                                  self.sumo) for ts in self.ts_ids}
        self.vehicles = dict()

        if self.single_agent:
            if return_info:
                return self._compute_observations()[self.ts_ids[0]], self._compute_info()
            else:
                return self._compute_observations()[self.ts_ids[0]]
        else:
            return self._compute_observations()
```
In previous versions of gym, the class `gym.Env` (which is a superclass of `SumoEnvironment`) there is only one method `reset()` with no arguments:
```python
    @abstractmethod
    def reset(self):
        """Resets the environment to an initial state and returns an initial
        observation.

        Note that this function should not reset the environment's random
        number generator(s); random variables in the environment's state should
        be sampled independently between multiple calls to `reset()`. In other
        words, each call of `reset()` should yield an environment suitable for
        a new episode, independent of previous episodes.

        Returns:
            observation (object): the initial observation.
        """
        raise NotImplementedError
```
So by calling a `super().reset(seed=seed, return_info=return_info, **kwargs)` not only do you pass an unexpected argument, but also raise `NotImplementedError`.
However, that should not the case with current version of gym.

**Comment by LucasAlegre** [comment]
SUMO-RL is currently supporting gym 0.24 (see https://github.com/LucasAlegre/sumo-rl/blob/master/setup.py).
