### ISSUE TITLE
plot.py ERROR

### ISSUE THREAD

**Issue by gioannides** [LucasAlegre/sumo-rl#115]
:~/Desktop/sumo-rl$ python outputs/plot.py -f experiments/outputs/sss/ -f multi_
Duplicate key in file '/home/user/.config/matplotlib/matplotlibrc', line 2 ('backend : Agg')
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/sumo_rl_pip/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'system_total_waiting_time'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "outputs/plot.py", line 88, in <module>
    ma=args.ma)
  File "outputs/plot.py", line 35, in plot_df
    df[yaxis] = pd.to_numeric(df[yaxis], errors='coerce')  # convert NaN string to NaN value
  File "/home/user/anaconda3/envs/sumo_rl_pip/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/user/anaconda3/envs/sumo_rl_pip/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'system_total_waiting_time'

**Comment by LucasAlegre** [comment]
It seems that you called the script incorrectly: `python outputs/plot.py -f experiments/outputs/sss/ -f multi_`

It is trying to read a file that is not a csv. I imagine you wanted something like `python outputs/plot.py -f experiments/outputs/sss/multi_` ?

**Comment by tonmoy-TS** [comment]
I had the exact similar problem.

I ran the ql_single-intersection.py script. I was trying to plot the results through this command:


`$ python outputs/plot.py -f experiments/outputs/single-intersection/single-intersection.csv`

and

`$ python outputs/plot.py -f experiments/outputs/single-intersection/single-intersection`

None of them worked, at showed the exact same errors:

``` 
Traceback (most recent call last):
  File "/home/joshuaogbebor/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'system_total_waiting_time'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "outputs/plot.py", line 82, in <module>
    plot_df(main_df,
  File "outputs/plot.py", line 35, in plot_df
    df[yaxis] = pd.to_numeric(df[yaxis], errors='coerce')  # convert NaN string to NaN value
  File "/home/joshuaogbebor/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/joshuaogbebor/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'system_total_waiting_time' ```

**Comment by LucasAlegre** [comment]
I believe this has been fixed already. Please re-open in case I am wrong @tonmoy-TS
