### ISSUE TITLE
Gym -> Gymnasium

### ISSUE THREAD

**Issue by smarianimore** [LucasAlegre/sumo-rl#127]
Dear everybody, 
I'm trying to run the examples provided as well as some simple code as suggested in the readme to get started, but I'm getting errors in every attempt. 

**Disclaimer**: I am collecting them here all together as I suspect they have to do with the transition from gym to gymnasium, which also affects related libraries such as stable-baselines3 and RLlib.
If this causes confusion I'll split everything into its own separate issue.

**Custom simple example**

The following code based on readme fails with `gymnasium.error.NameNotFound: Environment sumo-rl doesn't exist.`

````
import gymnasium as gym
import sumo_rl

env = gym.make('sumo-rl-v0',
                net_file='sumo-rl/nets/2way-single-intersection/single-intersection.net.xml',
                route_file='sumo-rl/nets/2way-single-intersection/single-intersection-vhvh.rou.xml',
                out_csv_name='sumo-rl/outputs/2way-single-intersection/dqn',
                use_gui=True,
                num_seconds=1000)
obs, info = env.reset()
done = False
while not done:
    next_obs, reward, terminated, truncated, info = env.step(env.action_space.sample())
    done = terminated or truncated
````

The following modification to environment creation (copied from DQN example) fails with `TypeError: reset() got an unexpected keyword argument 'seed'`

````
import gymnasium as gym
import sumo_rl
from sumo_rl import SumoEnvironment
import traci

env = SumoEnvironment(net_file='sumo-rl/nets/2way-single-intersection/single-intersection.net.xml',
                route_file='sumo-rl/nets/2way-single-intersection/single-intersection-vhvh.rou.xml',
                out_csv_name='sumo-rl/outputs/2way-single-intersection/dqn',
                use_gui=True,
                num_seconds=1000)
obs, info = env.reset()
done = False
while not done:
    next_obs, reward, terminated, truncated, info = env.step(env.action_space.sample())
    done = terminated or truncated
````

**Given examples**

Example `experiments/dqn_2way-single-intersection.py` fails with `TypeError: reset() got an unexpected keyword argument 'seed'`

Example `experiments/a3c_4x4grid.py` fails with (full log this time)

````
2022-12-13 11:18:56,785	INFO worker.py:1528 -- Started a local Ray instance.
/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
2022-12-13 11:18:59,771	INFO algorithm.py:2303 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also then want to set eager_tracing=True in order to reach similar execution speed as with static-graph mode.
2022-12-13 11:18:59,776	INFO algorithm.py:457 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(RolloutWorker pid=99278)  Retrying in 1 seconds
(RolloutWorker pid=99277)  Retrying in 1 seconds
Traceback (most recent call last):
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 524, in setup
    self.workers = WorkerSet(
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 139, in __init__
    self.add_workers(
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 490, in add_workers
    self.foreach_worker(lambda w: w.assert_healthy())
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 620, in foreach_worker
    remote_results = ray.get([w.apply.remote(func) for w in self.remote_workers()])
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/ray/_private/worker.py", line 2291, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=99278, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fd883b89dc0>)
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 492, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/sumo-rl/experiments/a3c_4x4grid.py", line 23, in <lambda>
    register_env("4x4grid", lambda _: PettingZooEnv(sumo_rl.env(net_file='nets/4x4-Lucas/4x4.net.xml',
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/sumo-rl/sumo_rl/environment/env.py", line 28, in env
    env = wrappers.AssertOutOfBoundsWrapper(env)
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/pettingzoo/utils/wrappers/assert_out_of_bounds.py", line 14, in __init__
    assert all(
AssertionError: should only use AssertOutOfBoundsWrapper for Discrete spaces

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/sumo-rl/experiments/a3c_4x4grid.py", line 29, in <module>
    trainer = A3C(env="4x4grid", config={
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 414, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 161, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/ray/rllib/algorithms/a3c/a3c.py", line 161, in setup
    super().setup(config)
  File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 549, in setup
    raise e.args[0].args[2]
AssertionError: should only use AssertOutOfBoundsWrapper for Discrete spaces
(RolloutWorker pid=99278) Step #0.00 (0ms ?*RT. ?UPS, TraCI: 48ms, vehicles TOT 0 ACT 0 BUF 0)                     
(RolloutWorker pid=99278) 2022-12-13 11:19:12,314	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=99278, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fd883b89dc0>)
(RolloutWorker pid=99278)   File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 492, in __init__
(RolloutWorker pid=99278)     self.env = env_creator(copy.deepcopy(self.env_context))
(RolloutWorker pid=99278)   File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/sumo-rl/experiments/a3c_4x4grid.py", line 23, in <lambda>
(RolloutWorker pid=99278)     register_env("4x4grid", lambda _: PettingZooEnv(sumo_rl.env(net_file='nets/4x4-Lucas/4x4.net.xml',
(RolloutWorker pid=99278)   File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/sumo-rl/sumo_rl/environment/env.py", line 28, in env
(RolloutWorker pid=99278)     env = wrappers.AssertOutOfBoundsWrapper(env)
(RolloutWorker pid=99278)   File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/pettingzoo/utils/wrappers/assert_out_of_bounds.py", line 14, in __init__
(RolloutWorker pid=99278)     assert all(
(RolloutWorker pid=99278) AssertionError: should only use AssertOutOfBoundsWrapper for Discrete spaces
(RolloutWorker pid=99277) Step #0.00 (0ms ?*RT. ?UPS, TraCI: 47ms, vehicles TOT 0 ACT 0 BUF 0)                     
(RolloutWorker pid=99277) 2022-12-13 11:19:12,314	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=99277, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fabdd28ad90>)
(RolloutWorker pid=99277)   File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 492, in __init__
(RolloutWorker pid=99277)     self.env = env_creator(copy.deepcopy(self.env_context))
(RolloutWorker pid=99277)   File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/sumo-rl/experiments/a3c_4x4grid.py", line 23, in <lambda>
(RolloutWorker pid=99277)     register_env("4x4grid", lambda _: PettingZooEnv(sumo_rl.env(net_file='nets/4x4-Lucas/4x4.net.xml',
(RolloutWorker pid=99277)   File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/sumo-rl/sumo_rl/environment/env.py", line 28, in env
(RolloutWorker pid=99277)     env = wrappers.AssertOutOfBoundsWrapper(env)
(RolloutWorker pid=99277)   File "/Users/sm/PycharmProjects/colasuonno/sumo-rl-tests/env/lib/python3.9/site-packages/pettingzoo/utils/wrappers/assert_out_of_bounds.py", line 14, in __init__
(RolloutWorker pid=99277)     assert all(
(RolloutWorker pid=99277) AssertionError: should only use AssertOutOfBoundsWrapper for Discrete spaces
````

I suspect it all has to do with the change to gym in gymnasium and some braking API changes they introduced in the latest versions...

What do you suggest?
If I install SUMO-RL from sources instead of pip the situation improves (as there are changes already rolled out there)?

**Comment by LucasAlegre** [comment]
Hi @smarianimore! 
Indeed all these errors are due to the change from Gym to Gymnasium. I have just released the current version of sumo-rl on pypi.

I have to update all the examples, but I'm still waiting for the RL libraries to finish migrating from Gym to Gymnasium first.

**Comment by LucasAlegre** [comment]
Hi @smarianimore ,

I've updated the examples and added instructions on how to use stable-baselines3 with Gymnasium in the README.
Please let me know if there are more issues.
