### ISSUE TITLE
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdownF 0)

### ISSUE THREAD

**Issue by dingshansun** [LucasAlegre/sumo-rl#158]
I was just trying to run the API example as given in the documentation with my own network.
However, an error occurred when the simulation time is over, which is:

Step #3600.00Error: tcpip::Socket::recvAndCheck @ recv: peer shutdownF 0)

Could you please give a hint about what the problem is and how to fix it?
Thank you!

I am using python 3.10.11 and SUMO 1.18.0 in windows

**Comment by dingshansun** [comment]
Just for your information, here is the entire error massage:

Step #3600.00Error: tcpip::Socket::recvAndCheck @ recv: peer shutdownF 0)
Exception ignored in: <function SumoEnvironment.__del__ at 0x000002046FDB7F40>
Traceback (most recent call last):
  File "C:\Users\dings\AppData\Local\Programs\Python\Python310\lib\site-packages\sumo_rl\environment\env.py", line 446, in __del__
Quitting (on error).
  File "C:\Users\dings\AppData\Local\Programs\Python\Python310\lib\site-packages\sumo_rl\environment\env.py", line 436, in close
  File "D:\Program Files (x86)\Eclipse\Sumo\tools\traci\main.py", line 262, in close
  File "D:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 396, in close
  File "D:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 231, in _sendCmd
  File "D:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 130, in _sendExact
OSError: [WinError 10038]
