### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'sumo'

### ISSUE THREAD

**Issue by wzFanM** [LucasAlegre/sumo-rl#159]
I failed on running the .py file in the experiment. 
Traceback (most recent call last):
  File "dqn_2way-single-intersection.py", line 19, in <module>
    env = SumoEnvironment(
  File "/home/XXX/anaconda3/envs/SUMO-RL/lib/python3.8/site-packages/sumo_rl/environment/env.py", line 149, in __init__
    traci.start([sumolib.checkBinary("sumo"), "-n", self._net], label="init_connection" + self.label)
  File "/home/XXX/anaconda3/envs/SUMO-RL/lib/python3.8/site-packages/traci/main.py", line 145, in start
    sumoProcess = subprocess.Popen(cmd2, stdout=stdout)
  File "/home/XXX/anaconda3/envs/SUMO-RL/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/XXX/anaconda3/envs/SUMO-RL/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sumo'

**Comment by LucasAlegre** [comment]
It seems you do not have installed the SUMO simulator

**Comment by wzFanM** [comment]
I install SUMO in linux in this link https://salsa.debian.org/science-team/sumo/-/tree/master
I am not sure if I install it successfully because I still have "FileNotFoundError: [Errno 2] No such file or directory: 'sumo'". 
Can you tell me how to install SUMO simulator?

**Comment by LucasAlegre** [comment]
There is instruction on how to install SUMO via terminal in the README (see https://github.com/LucasAlegre/sumo-rl#install-sumo-latest-version). 

You can also find more details at: https://sumo.dlr.de/docs/Installing/index.html
