### ISSUE TITLE
Unsuccessfully try on experiments\sarsa_2way-single-intersection.py

### ISSUE THREAD

**Issue by anochasut** [LucasAlegre/sumo-rl#166]
Hi, 

I'm a beginner. Just finished installation and go straight to try experiments.  

It seems like i must have missed something. Please advice.

===========
>>> python experiments/sarsa_2way-single-intersection.py
 Retrying in 1 seconds
Step #0.00 (0ms ?*RT. ?UPS, TraCI: 6ms, vehicles TOT 0 ACT 0 BUF 0)
 Retrying in 1 seconds
Traceback (most recent call last):
  File "/Project/sumo-rl/experiments/sarsa_2way-single-intersection.py", line 78, in <module>
    action = agent.act(obs)
  File "/Project/linear-rl-master/linear_rl/true_online_sarsa.py", line 71, in act
    features = self.get_features(obs)
  File "/Project/linear-rl-master/linear_rl/true_online_sarsa.py", line 63, in get_features
    return self.basis.get_features(state)
  File "/Project/linear-rl-master/linear_rl/fourier.py", line 33, in get_features
    return np.cos(np.dot(np.pi*self.coeff, state))
  File "<__array_function__ internals>", line 200, in dot
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
Exception ignored in: <function SumoEnvironment.__del__ at 0x7fcef5547820>
Traceback (most recent call last):
  File "/Project/sumo-rl/sumo_rl/environment/env.py", line 446, in __del__
  File "/Project/sumo-rl/sumo_rl/environment/env.py", line 436, in close
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/traci/main.py", line 262, in close
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/traci/connection.py", line 396, in close
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/traci/connection.py", line 231, in _sendCmd
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/traci/connection.py", line 130, in _sendExact
OSError: [Errno 9] Bad file descriptor
Step #0.00Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
malloc_consolidate(): unaligned fastbin chunk detected
===========

**Comment by LucasAlegre** [comment]
Hi @anochasut @hiXixi66 ,

This experiment was using the old gym API. I have just updated it in the last commit to use the correct API.

**Comment by anochasut** [comment]
Thank you so much Lucas!
