### ISSUE TITLE
Mac Setup

### ISSUE THREAD

**Issue by mainakchain** [LucasAlegre/sumo-rl#17]
Is there a way to run the package on MacOS? There seems to be some installation error.

```
Building wheels for collected packages: atari-py
  Building wheel for atari-py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7r/4053h7154wv3qw4pnqw4w8l40000gq/T/pip-install-ncx9h45m/atari-py/setup.py'"'"'; __file__='"'"'/private/var/folders/7r/4053h7154wv3qw4pnqw4w8l40000gq/T/pip-install-ncx9h45m/atari-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/7r/4053h7154wv3qw4pnqw4w8l40000gq/T/pip-wheel-h7mwui__
       cwd: /private/var/folders/7r/4053h7154wv3qw4pnqw4w8l40000gq/T/pip-install-ncx9h45m/atari-py/
  Complete output (502 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.15-x86_64-3.8
  creating build/lib.macosx-10.15-x86_64-3.8/atari_py
  copying atari_py/__init__.py -> build/lib.macosx-10.15-x86_64-3.8/atari_py
  copying atari_py/ale_python_interface.py -> build/lib.macosx-10.15-x86_64-3.8/atari_py
....
....
 copying atari_py/package_data.txt -> build/lib.macosx-10.15-x86_64-3.8/atari_py
  creating build/lib.macosx-10.15-x86_64-3.8/atari_py/tests
  copying atari_py/tests/__init__.py -> build/lib.macosx-10.15-x86_64-3.8/atari_py/tests
  copying atari_py/tests/test_smoke.py -> build/lib.macosx-10.15-x86_64-3.8/atari_py/tests
  running build_ext
  Traceback (most recent call last):
    File "/private/var/folders/7r/4053h7154wv3qw4pnqw4w8l40000gq/T/pip-install-ncx9h45m/atari-py/setup.py", line 22, in run
      subprocess.check_call(['cmake', '..'], cwd=cwd)
    File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 359, in check_call
      retcode = call(*popenargs, **kwargs)
    File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call
      with Popen(*popenargs, **kwargs) as p:
    File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
```

```
...
File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/7r/4053h7154wv3qw4pnqw4w8l40000gq/T/pip-install-ncx9h45m/atari-py/setup.py", line 28, in run
      sys.stderr.write("Unable to execute '{}'. HINT: are you sure `make` is installed?\n".format(' '.join(cmd)))
NameError: name 'cmd' is not defined
  ----------------------------------------
  ERROR: Failed building wheel for atari-py
  Running setup.py clean for atari-py
Failed to build atari-py
Installing collected packages: atari-py, ray, sumo-rl
    Running setup.py install for atari-py ... error
```

**Comment by LucasAlegre** [comment]
Hi,
This looks like a problem with gym installation. I would recommend checking https://github.com/openai/gym.

Cheers
