### ISSUE TITLE
SUMO-Crash during experiment with a simple Intersection from osmWebWizard

### ISSUE THREAD

**Issue by DrRembo** [LucasAlegre/sumo-rl#170]
Hello,

I created a simple intersection scenario with osmWebWzard.py and tried to start a sumo-rl experiment (see the files attached)
Unfortunately SUMO crashes with the following Error:

python3 myExperiment.py
 Retrying in 1 seconds
Step #0.00 (0ms ?*RT. ?UPS, TraCI: 4ms, vehicles TOT 0 ACT 0 BUF 0)
 Retrying in 1 seconds
Traceback (most recent call last):
  File "/Users/emanuel/SRL/sumo-rl/myExperiment.py", line 12, in <module>
    next_obs, reward, terminated, truncated, info = env.step(env.action_space.sample())
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gymnasium/wrappers/order_enforcing.py", line 56, in step
    return self.env.step(action)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gymnasium/wrappers/env_checker.py", line 51, in step
    return self.env.step(action)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emanuel/SRL/sumo-rl/sumo_rl/environment/env.py", line 311, in step
    self._run_steps()
  File "/Users/emanuel/SRL/sumo-rl/sumo_rl/environment/env.py", line 328, in _run_steps
    self._sumo_step()
  File "/Users/emanuel/SRL/sumo-rl/sumo_rl/environment/env.py", line 400, in _sumo_step
    self.sumo.simulationStep()
  File "/opt/homebrew/lib/python3.11/site-packa
ges/traci/connection.py", line 366, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/traci/connection.py", line 226, in _sendCmd
    return self._sendExact()
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/traci/connection.py", line 135, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO 

[myExperiment.zip](https://github.com/LucasAlegre/sumo-rl/files/13502797/myExperiment.zip)

**Comment by DrRembo** [comment]
I changed the tlLogic - tag in the net file from: 
<tlLogic id="483750" type="actuated" programID="0" offset="0">
to
<tlLogic id="483750" type="static" programID="0" offset="0">
and now sumo-rl works just fine :)
