### ISSUE TITLE
Issue with a3c_4x4 grid

### ISSUE THREAD

**Issue by mainakchain** [LucasAlegre/sumo-rl#18]
I have been trying to run the RLlib A3C multiagent in a 4x4 grid file **(experiments/a3c_4x4grid.py)** as mentioned in the documentation but every-time, I get this error. Can you please help me solve the issue? @LucasAlegre 

```WARNING:tensorflow:From /home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/tensorflow/python/compat/v2_compat.py:61: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-10-28 07:10:14,677	INFO services.py:1166 -- View the Ray dashboard at http://127.0.0.1:8265
/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
2020-10-28 07:10:15,750	INFO trainer.py:591 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
2020-10-28 07:10:15,750	INFO trainer.py:618 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
 Retrying in 1 seconds
Step #0.00 (0ms ?*RT. ?UPS, TraCI: 1ms, vehicles TOT 0 ACT 0 BUF 0)                      
(pid=19282) WARNING:tensorflow:From /home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/tensorflow/python/compat/v2_compat.py:61: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=19282) Instructions for updating:
(pid=19282) non-resource variables are not supported in the long term
(pid=19285) WARNING:tensorflow:From /home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/tensorflow/python/compat/v2_compat.py:61: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=19285) Instructions for updating:
(pid=19285) non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/tensorflow/python/ops/clip_ops.py:286: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
(pid=19285)  Retrying in 1 seconds
(pid=19282)  Retrying in 1 seconds
 Retrying in 1 seconds
2020-10-28 07:10:17,454	WARNING util.py:39 -- Install gputil for GPU system monitoring.
(pid=19285) Step #0.00 (0ms ?*RT. ?UPS, TraCI: 1ms, vehicles TOT 0 ACT 0 BUF 0)                      
(pid=19285) /home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
(pid=19285)   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
(pid=19282) /home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
(pid=19282)   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
(pid=19282) Step #0.00 (0ms ?*RT. ?UPS, TraCI: 1ms, vehicles TOT 0 ACT 0 BUF 0)                      
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 347, in run
    raise e
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 344, in run
    self._run()
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 369, in _run
    item = next(rollout_provider)
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 604, in _env_runner
    perf_stats=perf_stats,
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 798, in _process_observations
    policy_id).transform(raw_obs)
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 1486, in _get_or_raise
    "in policy map keys {}.".format(policy_id, mapping.keys()))
ValueError: Could not find policy for agent: agent policy id '0' not in policy map keys dict_keys(['default_policy']).

(pid=19285) WARNING:tensorflow:From /home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/tensorflow/python/ops/clip_ops.py:286: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
(pid=19285) Instructions for updating:
(pid=19285) Use tf.where in 2.0, which has the same broadcast rule as np.where
(pid=19282) WARNING:tensorflow:From /home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/tensorflow/python/ops/clip_ops.py:286: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
(pid=19282) Instructions for updating:
(pid=19282) Use tf.where in 2.0, which has the same broadcast rule as np.where
(pid=19285)  Retrying in 1 seconds
(pid=19282)  Retrying in 1 seconds
Traceback (most recent call last):
  File "a3c_4x4grid.py", line 47, in <module>
    print(trainer.train())  # distributed training step
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 516, in train
    raise e
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 505, in train
    result = Trainable.train(self)
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/tune/trainable.py", line 336, in train
    result = self.step()
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 134, in step
    res = next(self.train_exec_impl)
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/util/iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/util/iter.py", line 551, in base_iterator
    batch = ray.get(obj_ref)
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/worker.py", line 1428, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::RolloutWorker.par_iter_next_batch() (pid=19285, ip=10.14.31.64)
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 438, in ray._raylet.execute_task.function_executor
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/util/iter.py", line 1158, in par_iter_next_batch
    batch.append(self.par_iter_next())
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/util/iter.py", line 1152, in par_iter_next
    return next(self.local_it)
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 288, in gen_rollouts
    yield self.sample()
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 579, in sample
    batches = [self.input_reader.next()]
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 93, in next
    batches = [self.get_data()]
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 383, in get_data
    raise rollout
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 347, in run
    raise e
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 344, in run
    self._run()
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 369, in _run
    item = next(rollout_provider)
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 604, in _env_runner
    perf_stats=perf_stats,
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 798, in _process_observations
    policy_id).transform(raw_obs)
  File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 1486, in _get_or_raise
    "in policy map keys {}.".format(policy_id, mapping.keys()))
ValueError: Could not find policy for agent: agent policy id `0` not in policy map keys dict_keys(['default_policy']).
(pid=19285) Exception in thread Thread-1:
(pid=19285) Traceback (most recent call last):
(pid=19285)   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
(pid=19285)     self.run()
(pid=19285)   File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 347, in run
(pid=19285)     raise e
(pid=19285)   File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 344, in run
(pid=19285)     self._run()
(pid=19285)   File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 369, in _run
(pid=19285)     item = next(rollout_provider)
(pid=19285)   File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 604, in _env_runner
(pid=19285)     perf_stats=perf_stats,
(pid=19285)   File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 798, in _process_observations
(pid=19285)     policy_id).transform(raw_obs)
(pid=19285)   File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 1486, in _get_or_raise
(pid=19285)     "in policy map keys {}.".format(policy_id, mapping.keys()))
(pid=19285) ValueError: Could not find policy for agent: agent policy id `0` not in policy map keys dict_keys(['default_policy']).
(pid=19285) 
(pid=19282) Exception in thread Thread-1:
(pid=19282) Traceback (most recent call last):
(pid=19282)   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
(pid=19282)     self.run()
(pid=19282)   File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 347, in run
(pid=19282)     raise e
(pid=19282)   File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 344, in run
(pid=19282)     self._run()
(pid=19282)   File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 369, in _run
(pid=19282)     item = next(rollout_provider)
(pid=19282)   File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 604, in _env_runner
(pid=19282)     perf_stats=perf_stats,
(pid=19282)   File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 798, in _process_observations
(pid=19282)     policy_id).transform(raw_obs)
(pid=19282)   File "/home/rstudio/traffic_optimisation/sumo-rl/experiments/sumo/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 1486, in _get_or_raise
(pid=19282)     "in policy map keys {}.".format(policy_id, mapping.keys()))
(pid=19282) ValueError: Could not find policy for agent: agent policy id `0` not in policy map keys dict_keys(['default_policy']).
(pid=19282) 
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdownms, vehicles TOT 272 ACT 260 BUF 0
Quitting (on error)```

**Comment by LucasAlegre** [comment]
Hello, sorry for the delayed response.

I have just done a big refactor in the repository. This experiment should work now!

Cheers
