### ISSUE TITLE
QL Agent not running properly

### ISSUE THREAD

**Issue by prajwalvinod** [LucasAlegre/sumo-rl#182]
Hey @LucasAlegre,

I am trying to run the ql agent for the sumo environment that I have defined but I get the following error:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.2.5\plugins\python\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm 2023.2.5\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\prajw\PythonFiles\Thesis\RL_for_Freeway\Hegyi_Model\ql_test_1.py", line 41, in <module>
    ql_agents = {
                ^
  File "C:\Users\prajw\PythonFiles\Thesis\RL_for_Freeway\Hegyi_Model\ql_test_1.py", line 43, in <dictcomp>
    starting_state=env.encode(initial_states[ts], ts),
                              ~~~~~~~~~~~~~~^^^^
TypeError: tuple indices must be integers or slices, not str
Step #0.00 (0ms ?*RT. ?UPS, TraCI: 42809ms, vehicles TOT 0 ACT 0 BUF 0)                  

Process finished with exit code 1

```

The initial states for my environment are defined as follows:

```
This is init states (array([1., 0., 0., 0., 0., 0.], dtype=float32), {'step': 0.0, 'system_total_stopped': 0, 'system_total_waiting_time': 0, 'system_mean_waiting_time': 0.0, 'system_mean_speed': 0.0, 'J8_stopped': 0, 'J8_accumulated_waiting_time': 0.0, 'J8_average_speed': 1.0, 'agents_total_stopped': 0, 'agents_total_accumulated_waiting_time': 0.0})
```

Is there a reason why it is showing this error ?

Thanks 

P.S. Let me know if any python files are required.

**Comment by prajwalvinod** [comment]
Hey @LucasAlegre,

Any idea as to why the above is happening ?

Regards 

Prajwal

**Comment by LucasAlegre** [comment]
you are probably doing
initital_states = env.reset()
instead of 
initial_states, info = env.reset()

You can see on your print that it is printing both the states and the info dict

**Comment by prajwalvinod** [comment]
Hey @LucasAlegre,

I made that change but now there seems to be a new error as follows:

```
This is init states [1. 0. 0. 0. 0. 0.]
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.2.5\plugins\python\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm 2023.2.5\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\prajw\PythonFiles\Thesis\RL_for_Freeway\Hegyi_Model\ql_test_1.py", line 41, in <module>
    ql_agents = {
                ^
  File "C:\Users\prajw\PythonFiles\Thesis\RL_for_Freeway\Hegyi_Model\ql_test_1.py", line 43, in <dictcomp>
    starting_state=env.encode(initial_states[ts], ts),
                              ~~~~~~~~~~~~~~^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
Step #0.00 (0ms ?*RT. ?UPS, TraCI: 79245ms, vehicles TOT 0 ACT 0 BUF 0)                  

Process finished with exit code 1

```

Any insight into this ? As I feel that it is getting a valid array with integer values.

Regards

Prajwal

**Comment by prajwalvinod** [comment]
> you are probably doing initital_states = env.reset() instead of initial_states, info = env.reset()
> 
> You can see on your print that it is printing both the states and the info dict

Hey @LucasAlegre,

This particular caveat should probably be corrected or mentioned separately inline or otherwise since it is part of the QL code.
Just a small suggestion in case this is a common occurrence for a lot of people. 

Also any insight into the above comment.

Thanks

Prajwal

**Comment by prajwalvinod** [comment]
Hey @LucasAlegre,

After solving some of the above issues I now get a new error:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.2.5\plugins\python\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm 2023.2.5\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\prajw\PythonFiles\Thesis\RL_for_Freeway\Hegyi_Model\ql_test_1.py", line 65, in <module>
    s, r, done, info = env.step(action=actions)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajw\PythonFiles\Thesis\RL_for_Freeway\Hegyi_Model\env_disc.py", line 310, in step
    self._apply_actions(action)
  File "C:\Users\prajw\PythonFiles\Thesis\RL_for_Freeway\Hegyi_Model\env_disc.py", line 345, in _apply_actions
    self.traffic_signals[self.ts_ids[0]].set_next_phase(actions)
  File "C:\Users\prajw\PythonFiles\Thesis\RL_for_Freeway\Hegyi_Model\tls_discrete.py", line 165, in set_next_phase
    new_phase = int(new_phase)
                ^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'dict'

```

The **new_phase** variable for me is initialized as a dict as follows: ``` { 'J8': 0 } ``` where J8 is the traffic signal id.

How can I get over this issue ? And why does this not cause issues for other RL agents ?

Thanks

Prajwal

**Comment by prajwalvinod** [comment]
Hey @LucasAlegre,

All the above issues were solved by setting the ``` single agent = False ''' Now the Q-learning runs properly. Although I don't know why I am unable to run it properly for ''' single agent = True '''. 

Although the issue has been resolved, if you have some idea as to why this happens please let me know. I will leave this open for a couple of days and then close it.

Regards

Prajwal

**Comment by LucasAlegre** [comment]
When 'single_agent=True', the API expects the action to be an integer corresponding to the action of the single agent. When 'single_agent=False', it expects a dictionary mapping each agent to its action. You can check the API: https://github.com/LucasAlegre/sumo-rl/blob/main/sumo_rl/environment/env.py#L298

**Comment by prajwalvinod** [comment]
I got that from the description which is why I changed it and found it to be running.

Thanks  

Prajwal
