### ISSUE TITLE
Error of  running a3c_4*4grid.py about ray

### ISSUE THREAD

**Issue by lylyjy** [LucasAlegre/sumo-rl#26]
When I run a3c_4*4grid.py, it occurs that:

Exception has occurred: RayTaskError
[36mray::RolloutWorker.foreach_policy()[39m (pid=590, ip=192.168.1.106)
  File "python/ray/_raylet.pyx", line 450, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 453, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 474, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 343, in ray._raylet.raise_if_dependency_failed
ray.exceptions.RaySystemError: System error: No module named 'environment'
traceback: Traceback (most recent call last):
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/ray/serialization.py", line 242, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/ray/serialization.py", line 188, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/ray/serialization.py", line 166, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/ray/serialization.py", line 156, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
ModuleNotFoundError: No module named 'environment'
  File "/mnt/d/try/sumo-rl-master/experiments/a3c_4x4grid.py", line 32, in <module>
    trainer = A3CTrainer(env="4x4grid", config={

Can you help me how to solve it? Thanks.

**Comment by zzchuman** [comment]
> When I run a3c_4*4grid.py, it occurs that:
> 
> Exception has occurred: RayTaskError
> �[36mray::RolloutWorker.foreach_policy()�[39m (pid=590, ip=192.168.1.106)
> File "python/ray/_raylet.pyx", line 450, in ray._raylet.execute_task
> File "python/ray/_raylet.pyx", line 453, in ray._raylet.execute_task
> File "python/ray/_raylet.pyx", line 474, in ray._raylet.execute_task
> File "python/ray/_raylet.pyx", line 343, in ray._raylet.raise_if_dependency_failed
> ray.exceptions.RaySystemError: System error: No module named 'environment'
> traceback: Traceback (most recent call last):
> File "/home/lyl/miniconda3/lib/python3.8/site-packages/ray/serialization.py", line 242, in deserialize_objects
> obj = self._deserialize_object(data, metadata, object_ref)
> File "/home/lyl/miniconda3/lib/python3.8/site-packages/ray/serialization.py", line 188, in _deserialize_object
> return self._deserialize_msgpack_data(data, metadata_fields)
> File "/home/lyl/miniconda3/lib/python3.8/site-packages/ray/serialization.py", line 166, in _deserialize_msgpack_data
> python_objects = self._deserialize_pickle5_data(pickle5_data)
> File "/home/lyl/miniconda3/lib/python3.8/site-packages/ray/serialization.py", line 156, in _deserialize_pickle5_data
> obj = pickle.loads(in_band)
> ModuleNotFoundError: No module named 'environment'
> File "/mnt/d/try/sumo-rl-master/experiments/a3c_4x4grid.py", line 32, in
> trainer = A3CTrainer(env="4x4grid", config={
> 
> Can you help me how to solve it? Thanks.

Hello Can discuss the a3c 4x4 with you？

**Comment by Laudarisd** [comment]
Hi, did you solve this problem?
I got the same error
```
pid=272361) /home/administrator/.local/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
(pid=272361)   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "experiments/a3c_4x4grid.py", line 30, in <module>
    trainer = A3CTrainer(env="4x4grid", config={
  File "/home/administrator/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 123, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/administrator/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 584, in __init__
    super().__init__(config, logger_creator)
  File "/home/administrator/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 103, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/administrator/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 731, in setup
    self._init(self.config, self.env_creator)
  File "/home/administrator/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 147, in _init
    self.workers = self._make_workers(
  File "/home/administrator/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 813, in _make_workers
    return WorkerSet(
  File "/home/administrator/.local/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 84, in __init__
    remote_spaces = ray.get(self.remote_workers(
  File "/home/administrator/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/administrator/.local/lib/python3.8/site-packages/ray/worker.py", line 1566, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=272365, ip=192.168.0.240)
  File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task.function_executor
  File "/home/administrator/.local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/administrator/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 712, in __init__
    "Created rollout worker with env {} ({}), policies {}".format(
  File "/home/administrator/.local/lib/python3.8/site-packages/gym/core.py", line 150, in __str__
    return '<{}<{}>>'.format(type(self).__name__, self.spec.id)
AttributeError: 'str' object has no attribute 'id'

```
@zzchuman @LucasAlegre @lylyjy 

Thanks
