### ISSUE TITLE
plot prolem

### ISSUE THREAD

**Issue by yuy01** [LucasAlegre/sumo-rl#38]
After i ran ql_single-intersection.py, it generate the file "2021-05-06 13:52:39_alpha0.1_gamma0.99_eps0.05_decay1.0_run1.csv", then i need to plot, follow as written in readme file:

Plotting results:
python3 outputs/plot.py -f outputs/2way-single-intersection/a3c 

i ran "python3 outputs/plot.py -f outputs/2way-single-intersection/2021-05-06 13:52:39_alpha0.1_gamma0.99_eps0.05_decay1.0_run1.csv" and "python3 outputs/plot.py -f outputs/2way-single-intersection/a3c", 

it returns:

MS-7C98:~/project/traffic_rl/sumo-rl-master$ python3 outputs/plot.py -f outputs/single-intersection/2021-05-06 13:52:39_alpha0.1_gamma0.99_eps0.05_decay1.0_run1.csv
Traceback (most recent call last):
  File "/home/program/anaconda3/envs/tf114/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'total_wait_time'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "outputs/plot.py", line 87, in <module>
    ma=args.ma)
  File "outputs/plot.py", line 35, in plot_df
    df[yaxis] = pd.to_numeric(df[yaxis], errors='coerce')  # convert NaN string to NaN value
  File "/home/program/anaconda3/envs/tf114/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/program/anaconda3/envs/tf114/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'total_wait_time'

**Comment by yuy01** [comment]
I solved the problem, it was due to the wrong file path parsing.

**Comment by zzchuman** [comment]
> I solved the problem, it was due to the wrong file path parsing.

Hello , can I ask some questions about this code?

**Comment by zzchuman** [comment]
> I solved the problem, it was due to the wrong file path parsing.

你好，可以向你请教这篇代码吗

**Comment by luckywlj** [comment]
> I solved the problem, it was due to the wrong file path parsing.
Can you  explain your answer? Where is the wrong file path parsing? I check many times and don't find the wrong file path. Thank you!
