### ISSUE TITLE
Odd error message

### ISSUE THREAD

**Issue by jkterry1** [LucasAlegre/sumo-rl#57]
Hey, I'm trying to train with SB3 and sumo (which I installed via the installation instructions in the readme) and am getting the following error message:

```
Warning: Deprecated vehicle classes 'rail_fast' in input network.
========== LunarLanderContinuous-v2 ==========
Seed: 1705882364
Default hyperparameters for environment (ones being tuned will be overridden):
OrderedDict([('batch_size', 64),
             ('ent_coef', 0.01),
             ('gae_lambda', 0.98),
             ('gamma', 0.999),
             ('n_envs', 16),
             ('n_epochs', 4),
             ('n_steps', 1024),
             ('n_timesteps', 1000000.0),
             ('policy', 'MlpPolicy')])
Using 4 environments
Overwriting n_timesteps with n=5000000
 Retrying in 1 seconds
Traceback (most recent call last):
  File "train.py", line 288, in <module>
    model = exp_manager.setup_experiment()
  File "/home/j_k_terry/rl-baselines3-zoo/utils/exp_manager.py", line 200, in setup_experiment
    env = self.create_envs(self.n_envs, no_log=False)
  File "/home/j_k_terry/rl-baselines3-zoo/utils/exp_manager.py", line 544, in create_envs
    env = sumo_rl.ingolstadt7()
  File "/home/j_k_terry/sumo-rl/sumo_rl/environment/resco_envs.py", line 106, in ingolstadt7
    return parallel_env(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pettingzoo/utils/conversions.py", line 12, in par_fn
    env = env_fn(**kwargs)
  File "/home/j_k_terry/sumo-rl/sumo_rl/environment/env.py", line 29, in env
    env = SumoEnvironmentPZ(**kwargs)
  File "/home/j_k_terry/sumo-rl/sumo_rl/environment/env.py", line 290, in __init__
    self.env = SumoEnvironment(**self._kwargs)
  File "/home/j_k_terry/sumo-rl/sumo_rl/environment/env.py", line 98, in __init__
    conn) for ts in self.ts_ids}
  File "/home/j_k_terry/sumo-rl/sumo_rl/environment/env.py", line 98, in <dictcomp>
    conn) for ts in self.ts_ids}
  File "/home/j_k_terry/sumo-rl/sumo_rl/environment/traffic_signal.py", line 43, in __init__
    self.build_phases()
  File "/home/j_k_terry/sumo-rl/sumo_rl/environment/traffic_signal.py", line 85, in build_phases
    programs = self.sumo.trafficlight.getAllProgramLogics(self.id)
AttributeError: 'TrafficLightDomain' object has no attribute 'getAllProgramLogics'
Step #0.00Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
```

I googled the error and found this issue (https://github.com/LucasAlegre/sumo-rl/issues/46), however the fix you suggested there does not appear to apply? See the following:

```
j_k_terry@hyperparameter-tuning-7:~/rl-baselines3-zoo/optimize_logs$ apt-cache policy sumo
sumo:
  Installed: 1.1.0+dfsg1-1
  Candidate: 1.1.0+dfsg1-1
  Version table:
 *** 1.1.0+dfsg1-1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by LucasAlegre** [comment]
Hey, I believe this is an older SUMO version. I get:

```
sumo --version
Eclipse SUMO Version 1.4.0
 Build features: x86_64-pc-linux-gnu GDAL GUI
 Copyright (C) 2001-2019 German Aerospace Center (DLR) and others; https://sumo.dlr.de

Eclipse SUMO Version 1.4.0 is part of SUMO.
This program and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0
```

Maybe their ppa is not updated for Debian? I'm not sure, you can try to download an updated version from their repository perhaps.

**Comment by jkterry1** [comment]
Thanks a ton!

So the issue turned out to be that there's a sumo community debian/ubuntu PPA thing (which publishes for every supported version of debian/ubuntu /except/ debian 10, which I have to use), so nothing installed, but there's a very out of date official debian build of sumo that was installed instead. I'm currently building from source.
