### ISSUE TITLE
Execution error in a3c_4x4grid.py

### ISSUE THREAD

**Issue by luckywlj** [LucasAlegre/sumo-rl#71]
Hi, Lucas. First of all, I  am appreciate for your contribution. I finished the configuration and run the test command according to the README.md. When I run "python3 experiments/a3c_4x4grid.py" ,there are errors as follows:

(sumo-rl) luckywlj@luckywlj-MS-7982:~/sumo-rl-master$ python3 experiments/a3c_4x4grid.py 
Using libsumo as traci as requested by environment variable.
/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/_private/services.py:238: UserWarning: Not all Ray Dashboard dependencies were found. To use the dashboard please install Ray using `pip install ray[default]`. To disable this message, set RAY_DISABLE_IMPORT_WARNING env var to '1'.
  warnings.warn(warning_message)
/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/gym/spaces/box.py:74: UserWarning: WARN: Box bound precision lowered by casting to float32
  "Box bound precision lowered by casting to {}".format(self.dtype)
2021-12-22 10:04:26,708	INFO trainer.py:714 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
2021-12-22 10:04:26,708	INFO trainer.py:728 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=10814) Using libsumo as traci as requested by environment variable.
(pid=10813) Using libsumo as traci as requested by environment variable.
(pid=10813) /home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/pettingzoo/utils/wrappers/base.py:44: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.
(pid=10813)   warnings.warn("The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.")
(pid=10813) /home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/pettingzoo/utils/wrappers/base.py:52: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.
(pid=10813)   warnings.warn("The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.")
(pid=10814) /home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/pettingzoo/utils/wrappers/base.py:44: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.
(pid=10814)   warnings.warn("The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.")
(pid=10814) /home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/pettingzoo/utils/wrappers/base.py:52: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.
(pid=10814)   warnings.warn("The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.")
(pid=10814) 2021-12-22 10:04:29,622	WARNING deprecation.py:39 -- DeprecationWarning: `policy_mapping_fn(agent_id)` has been deprecated. Use `policy_mapping_fn(agent_id, episode, **kwargs)` instead. This will raise an error in the future!
2021-12-22 10:04:30,219	WARNING util.py:55 -- Install gputil for GPU system monitoring.
Traceback (most recent call last):
  File "experiments/a3c_4x4grid.py", line 41, in <module>
    print(trainer.train())  # distributed training step
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 648, in train
    raise e
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 637, in train
    result = Trainable.train(self)
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/tune/trainable.py", line 237, in train
    result = self.step()
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 193, in step
    res = next(self.train_exec_impl)
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/util/iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/util/iter.py", line 551, in base_iterator
    batch = ray.get(obj_ref)
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/worker.py", line 1621, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::RolloutWorker.par_iter_next_batch() (pid=10813, ip=192.168.1.120, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fbe6481ed90>)
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/util/iter.py", line 1157, in par_iter_next_batch
    batch.append(self.par_iter_next())
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/util/iter.py", line 1151, in par_iter_next
    return next(self.local_it)
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/util/iter.py", line 791, in apply_foreach
    result = fn(item)
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/rllib/execution/rollout_ops.py", line 122, in samples_to_grads
    return get_global_worker().compute_gradients(samples), samples.count
  File "/home/luckywlj/anaconda3/envs/sumo-rl/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 856, in compute_gradients
    if self.tf_sess is not None:
AttributeError: 'RolloutWorker' object has no attribute 'tf_sess'

I search the answer in google  and don't find the proper answer. Could you give me some suggestions ?

**Comment by luckywlj** [comment]
I check all issues about Execution error in a3c_4x4grid.py  and don't find the answer.

**Comment by luckywlj** [comment]
I checked the README again and found there was no ray folder in main folder. a3c_4x4grid.py imoprt A3CTFPolicy from ray.rllib.agents.a3c.a3c_tf_policy.  I put ray folder in the sumo-rl-master folder. But this error still occurs.

**Comment by luckywlj** [comment]
I see.The problem is about tensorflow version. Tendorflow 2.0 discard the  Session module.
